[[main]]
	name	=	"橄榄菜的博客"
	pageRef	=	'/'
	weight	=	1

[[main]]
	name	=	"友链"
	pageRef	=	'/friendlinks/'
	weight	=	2

[[main]]
	name	=	"关于"
	pageRef	=	'/aboutme/'
	weight	=	3

[[main]]
	name	=	"镜像站"
	pageRef	=	'/mirrors/'
	weight	=	4
