{
    "dns": {
        "rules": [
            {
                "rule_set": [
                    "geosite-cn"
                ],
                "server": "local"
            },
            {
                "rule_set": [
                    "category-ads-all"
                ],
                "server": "block"
            }
        ],
        "servers": [
            {
                "address": "1.1.1.1",
                "detour": "ganlanc.at",
                "tag": "remote"
            },
            {
                "address": "https://223.5.5.5/dns-query",
                "detour": "direct",
                "tag": "local"
            },
            {
                "address": "rcode://refused",
                "tag": "block"
            }
        ],
        "final": "remote",
        "strategy": "ipv4_only"
    },
    "inbounds": [
        {
            "auto_route": true,
            "domain_strategy": "prefer_ipv4",
            "endpoint_independent_nat": true,
            "address": [
                "172.19.0.1/30",
                "2001:0470:f9da:fdfa::1/64"
            ],
            "mtu": 9000,
            "sniff_override_destination": true,
            "stack": "system",
            "strict_route": true,
            "type": "tun"
        }
    ],
    "outbounds": [
        {
            "type": "direct",
            "tag": "direct"
        },
        {
            "server": "77.90.15.183",
            "server_port": 443,
            "password": "oinxio",
            "type": "trojan",
            "tag": "ganlanc.at",
            "tls": {
                "enabled": true,
                "server_name": "ganlanc.at",
                "insecure": true,
                "utls": {
                    "enabled": true,
                    "fingerprint": "chrome"
                }
            }
        }
    ],
    "route": {
        "auto_detect_interface": true,
        "rules": [
            {
                "action": "sniff"
            },
            {
                "protocol": "dns",
                "action": "hijack-dns"
            },
            {
                "rule_set": [
                    "geosite-cn",
                    "geoip-cn"
                ],
                "outbound": "direct"
            },
            {
                "ip_is_private": true,
                "outbound": "direct"
            },
            {
                "rule_set": [
                    "category-ads-all"
                ],
                "action": "reject"
            },
            {
              "outbound": "ganlanc.at"
            }
        ],
        "rule_set": [
            {
                "tag": "geosite-cn",
                "type": "remote",
                "format": "binary",
                "url": "https://gh-proxy.org/raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs",
                "download_detour": "direct"
            },
            {
                "tag": "category-ads-all",
                "type": "remote",
                "format": "binary",
                "url": "https://gh-proxy.org/raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all.srs",
                "download_detour": "direct"
            },
            {
                "tag": "geoip-cn",
                "type": "remote",
                "format": "binary",
                "url": "https://gh-proxy.org/raw.githubusercontent.com/Loyalsoldier/geoip/release/srs/cn.srs",
                "download_detour": "direct"
            }
        ]
    }
}
